baseUrl = "https://guillearch.me/"
languageCode = "es-es"
title = "Guillermo Castellano"
theme = "hello-friend"
copyright = ""
paginate = 5
rssLimit = 20

[params]
#  subtitle = "Your site subtitle"

#[params.logo]
#  path = ""
#  alt = "Guillermo Castellano"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Acerca de mí"
    url = "/about"
  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url = "/contact"
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/post/index.xml"

[permalinks]
    post = "/:year/:month/:title/"
